//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWeb.ComplianceAdministration.UserControl {
    
    
    public partial class AdminEntryAcctSettingPermissions {
        
        /// <summary>
        /// pnlAdminEntryAcctSetting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlAdminEntryAcctSetting;
        
        /// <summary>
        /// lblApplicantInviteStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblApplicantInviteStatus;
        
        /// <summary>
        /// ddlApplicantInviteStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlApplicantInviteStatus;
        
        /// <summary>
        /// rfvApplicantInviteStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApplicantInviteStatus;
        
        /// <summary>
        /// lblDays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDays;
        
        /// <summary>
        /// ntxtDays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclNumericTextBox ntxtDays;
        
        /// <summary>
        /// rbtnAppInviteActive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnAppInviteActive;
        
        /// <summary>
        /// rbtnOrderActive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnOrderActive;
        
        /// <summary>
        /// rbtnHoldStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnHoldStatus;
        
        /// <summary>
        /// fsucCmdBarVendorAcctSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.Shell.Views.CommandBar fsucCmdBarVendorAcctSettings;
    }
}
