declare var window: any;
export const environment = {
  production: false,
  //baseApiUrl: "http://172.17.3.77:8099",
  baseApiUrl: "http://localhost:59767", //Local host ,
  //baseApiUrl: window.location.origin + '/MobileWebApi', //For Production or Qa (For IOS)  //For Production or Qa
  AccountToLinkSelected: '/UserRegistration/AccountSelected',
  ApplicantUploadDocument: '/ApplicantApi/UploadApplicantDocument',
  AuthenticateUrl: '/GetAuthToken',
  CancelOrder: '/ApplicantOrderFlow/CancelBkgOrder',
  ChangePaymentTypeSubmitOrder: '/ApplicantOrderFlow/ChangePaymentTypeSubmitOrder',
  CompleteApplicantOrder: '/ApplicantOrderFlow/CompleteApplicantOrder',
  CreateHtmlFile: '/ApplicantOrderFlow/CreateHtmlFile',
  DownloadOrderReceipt: '/ApplicantOrderFlow/DownloadOrderReceipt',
  GenerateVerificationCode: 'CommonApi/GenerateVerificationCode',
  GetAgreementText: '/ApplicantOrderFlow/GetAgreementText',
  GetApplicantPackageCategoryDetails: '/ApplicantApi/GetApplicantPackageCategoryDetails',
  GetApplicantPackageList: '/ApplicantApi/GetApplicantPackageList',
  GetAppointmentSlots: '/ApplicantOrderFlow/GetAppointmentSlotsAvailable',
  GetAuthNetToken: '/ApplicantOrderFlow/GetAuthorizeNetToken',
  GetAuthorizedData: '/ApplicantApi/GetAuthorizedData',
  GetBillingCodeAmount: '/ApplicantOrderFlow/GetBillingCodeAmount',
  GetCascadingAttributeData: '/ApplicantOrderFlow/GetCascadingAttributeData',
  GetCbiUrlInfo: '/UserRegistration/IsLocationServiceTenant',
  GetCustomAppributesForOrderID: '/ApplicantOrderFlow/GetCustomAppributesForOrderID',
  GetCities: '/Lookup/GetAllCitiesByStateId',
  GetCommLanguage: '/Lookup/GetCommLanguage',
  GetCountryList: '/LookUp/GetCountriesList',
  GetCounty: '/Lookup/GetAllCountyByZipcodeId',
  GetCustomAttributeOptions: '/ApplicantOrderFlow/GetCustomAttributeOptions',
  GetClientSettingCustomAttribute: '/UserRegistration/GetClientSettingCustomAttribute',
  GetCustomerPaymentProfiles: '/ApplicantOrderFlow/GetCustomerPaymentProfiles',
  GetDefaultZipcode: '/ApplicantOrderFlow/DefaultZipcode',
  GetGender: '/Lookup/GetGender',
  GetInstructionText: '/ApplicantOrderFlow/GetMasterPaymentSetting',
  GetLocalizedDateFormat: '/ApplicantOrderFlow/GetLocalizedDateFormat',
  GetLocalizedGenderName: '/ApplicantOrderFlow/GetLocalizedGenderName',
  GetLocations: '/ApplicantOrderFlow/GetAvaliableLocations',
  GetMailingInfo: '/ApplicantOrderFlow/GetConditionsforCustomAttributes',
  GetOrderFlowPackages: '/ApplicantOrderFlow/GetOrderFlowPackages',
  GetOrderHistoryDetails: '/ApplicantOrderFlow/GetOrderHistoryDetails',
  GetOrderNumberDetails: '/ApplicantOrderFlow/GetOrderNumberDetails',
  GetOrganizationUser: '/ApplicantOrderFlow/GetOrganizationUser',
  GetOutOfStateLocation: '/ApplicantOrderFlow/GetOutOfStateLocation',
  GetPaymentOptions: '/ApplicantOrderFlow/GetPaymentOptions',
  GetPrice: '/ApplicantOrderFlow/GetTotalPrice',
  GetServiceDescription: '/ApplicantOrderFlow/GetServiceDescription',
  GetServiceDetails: '/ApplicantOrderFlow/GetCustomAttribute',
  GetStates: '/Lookup/GetStatesByCountryID',
  GetTenantName: '/CommonApi/GetTenantName',
  GetTranslatedList: '/CommonApi/GetTranslatedList',
  GetZipCodes: '/Lookup/GetZipCodesForSelectedState',
  GetAccountVerificationSettings: '/UserRegistration/GetAccountVerificationSettings',
  GetAccountVerficationQuestions: '/UserRegistration/GetAccountVerficationQuestions',
  LinkAccount: '/UserRegistration/LinkAccount',
  RegisterUser: '/UserRegistration/CreateUserAccount',
  RemoveCustomerCard: '/ApplicantOrderFlow/DeleteCustomerCard',
  RescheduleAppointment: '/ApplicantOrderFlow/RescheduleAppointment',
  ReserveSlot: '/ApplicantOrderFlow/ReserveSlot',
  SubmitOrder: '/ApplicantOrderFlow/SubmitOrder', 
  SubmitPayment: '/ApplicantOrderFlow/SubmitPayment',
  SubmitUserRegistration: '/Lookup/TestMethod',
  UserExists: '/UserRegistration/CheckUserName',
  UpdatePassword: 'CommonApi/UpdatePassword',
  ValidateEventCodeStatusAndEventDetails: '/ApplicantOrderFlow/GetValidateEventCodeStatusAndEventDetails',
  ValidateUniqueCbiId: '/ApplicantOrderFlow/IsValidCBIUniqueID',
  ValidateUserViaEmailAndRedirect: '/UserRegistration/ValidateUserViaEmailAndRedirect',
  ValidateandActivateUser: '/UserRegistration/ValidateandActivateUser',
  ValidateVerificationCode: '/CommonApi/ValidateVerificationCode',
  GetLocationImages: '/ApplicantOrderFlow/GetLocationImages',
  SubmitUserDetails: '/ApplicantOrderFlow/AddUpdateUser',
  ChangePassword: 'CommonApi/ChangePassword',
  IsPasswordExpired: '/CommonApi/IsPasswordExpired',  
  GetCBIUniqueIdByAcctNameOrNumber: '/ApplicantOrderFlow/GetCBIUniqueIdByAcctNameOrNumber',
  IsSuffixDropDown:'/CommonApi/IsSuffixDropDown',
  GetSuffixDropDown:'/Lookup/GetSuffixDropDown',
  IsReservedSlotExpired: '/ApplicantOrderFlow/IsReservedSlotExpired',
};
export const timerValue = 1800;

