//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWeb.PlacementMatching.Views {
    
    
    public partial class SearchRequest {
        
        /// <summary>
        /// rprxEditProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclResourceManagerProxy rprxEditProfile;
        
        /// <summary>
        /// lblSearchRequest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSearchRequest;
        
        /// <summary>
        /// pnlSearchRequest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSearchRequest;
        
        /// <summary>
        /// ddlTenantName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlTenantName;
        
        /// <summary>
        /// rfvTenantName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTenantName;
        
        /// <summary>
        /// ddlLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlLocation;
        
        /// <summary>
        /// ddlDepartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlDepartment;
        
        /// <summary>
        /// dtStartDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclDatePicker dtStartDate;
        
        /// <summary>
        /// ddlSpecialty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlSpecialty;
        
        /// <summary>
        /// ddlStudentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlStudentType;
        
        /// <summary>
        /// txtMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclNumericTextBox txtMax;
        
        /// <summary>
        /// dtEndDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclDatePicker dtEndDate;
        
        /// <summary>
        /// ddlRequestStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlRequestStatus;
        
        /// <summary>
        /// ddlDays control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlDays;
        
        /// <summary>
        /// ddlShift control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox ddlShift;
        
        /// <summary>
        /// caCustomAttributesID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.ClinicalRotation.Views.SharedUserCustomAttributeForm caCustomAttributesID;
        
        /// <summary>
        /// fsucCmdBarButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.Shell.Views.CommandBar fsucCmdBarButton;
        
        /// <summary>
        /// ColumnsConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.CommonControls.Views.ColumnsConfiguration ColumnsConfiguration;
        
        /// <summary>
        /// grdPlacementMatchingMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclGrid grdPlacementMatchingMapping;
        
        /// <summary>
        /// btnDoPostback control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDoPostback;
        
        /// <summary>
        /// hdnRequestId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnRequestId;
        
        /// <summary>
        /// hdnOpportuityID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnOpportuityID;
        
        /// <summary>
        /// hdnPageRequested control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnPageRequested;
        
        /// <summary>
        /// hdnIsSearchClicked control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnIsSearchClicked;
        
        /// <summary>
        /// hdnSelectedTenantID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedTenantID;
        
        /// <summary>
        /// hdnRequestSavedSuccessfully control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnRequestSavedSuccessfully;
        
        /// <summary>
        /// hdnRequestPublishedSuccessfully control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnRequestPublishedSuccessfully;
    }
}
