//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWeb.ComplianceAdministration.Views {
    
    
    public partial class SetupUniversalMapping {
        
        /// <summary>
        /// rprxetupUniversalMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclResourceManagerProxy rprxetupUniversalMapping;
        
        /// <summary>
        /// sptrContentPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclSplitter sptrContentPage;
        
        /// <summary>
        /// pnMainToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclPane pnMainToolbar;
        
        /// <summary>
        /// lblPageHdr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPageHdr;
        
        /// <summary>
        /// lblModHdr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblModHdr;
        
        /// <summary>
        /// breadcrum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.PageBreadCrumb breadcrum;
        
        /// <summary>
        /// pnMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclPane pnMain;
        
        /// <summary>
        /// sptrPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclSplitter sptrPage;
        
        /// <summary>
        /// pnUpper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclPane pnUpper;
        
        /// <summary>
        /// updpnlTree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updpnlTree;
        
        /// <summary>
        /// hdnDefaultScreen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnDefaultScreen;
        
        /// <summary>
        /// hdnSelectedNodeScreen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedNodeScreen;
        
        /// <summary>
        /// treeUniversalMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclTreeView treeUniversalMapping;
        
        /// <summary>
        /// mnuTreeCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTreeViewContextMenu mnuTreeCategory;
        
        /// <summary>
        /// btnUpdateTree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdateTree;
        
        /// <summary>
        /// WclSplitBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclSplitBar WclSplitBar1;
        
        /// <summary>
        /// pnLower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclPane pnLower;
        
        /// <summary>
        /// ifrDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlIframe ifrDetails;
        
        /// <summary>
        /// hdnSelectedNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedNode;
    }
}
