//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWeb.AgencyHierarchy.Views {
    
    
    public partial class AgencyHierarchyControls {
        
        /// <summary>
        /// rmpHierarchyControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclResourceManagerProxy rmpHierarchyControls;
        
        /// <summary>
        /// WclButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclButton WclButton1;
        
        /// <summary>
        /// btnAddNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclButton btnAddNode;
        
        /// <summary>
        /// dvAddNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvAddNode;
        
        /// <summary>
        /// pnlAddNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlAddNode;
        
        /// <summary>
        /// cmbAgencyNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INTERSOFT.WEB.UI.WebControls.WclComboBox cmbAgencyNode;
        
        /// <summary>
        /// rfvAgencyNode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAgencyNode;
        
        /// <summary>
        /// cmdBarSaveNodeMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.Shell.Views.CommandBar cmdBarSaveNodeMapping;
        
        /// <summary>
        /// hdnAddedRootNodeIdTemp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnAddedRootNodeIdTemp;
        
        /// <summary>
        /// ucMappedNodes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchyMappedNodes ucMappedNodes;
        
        /// <summary>
        /// ucAgencyHierarchyNodeAvailabilitySetting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchyNodeAvailabilitySetting ucAgencyHierarchyNodeAvailabilitySetting;
        
        /// <summary>
        /// ctrAgencyNodeMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyNodeMapping ctrAgencyNodeMapping;
        
        /// <summary>
        /// AgencyHierarchyUserPermission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchyUserPermission AgencyHierarchyUserPermission;
        
        /// <summary>
        /// ManageAgencyHierarchyPackage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.ManageAgencyHierarchyPackage ManageAgencyHierarchyPackage;
        
        /// <summary>
        /// ucSchoolNodeAssociation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.UserControls.SchoolNodeAssociation ucSchoolNodeAssociation;
        
        /// <summary>
        /// ucManageAgencyHierarchyTenantAccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.ManageAgencyHierarchyTenantAccess ucManageAgencyHierarchyTenantAccess;
        
        /// <summary>
        /// ucAgencyHierarchyRotationFieldOption control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchyRotationFieldOption ucAgencyHierarchyRotationFieldOption;
        
        /// <summary>
        /// ucManageRequirementApprovalNotificationDocument control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.UserControls.ManageRequirementApprovalNotificationDocument ucManageRequirementApprovalNotificationDocument;
        
        /// <summary>
        /// ucAgencyHierarchySetting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchySetting ucAgencyHierarchySetting;
        
        /// <summary>
        /// ucAttestationFormSetting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.ManageAttestationFormDocument ucAttestationFormSetting;
        
        /// <summary>
        /// ucAgencyHierarchyRootNodeSetting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CoreWeb.AgencyHierarchy.Views.AgencyHierarchyRootNodeSetting ucAgencyHierarchyRootNodeSetting;
    }
}
